### ISSUE TITLE
Why subtract the bias?

### ISSUE THREAD

**Issue by FloCF** [NVIDIA/partialconv#18]
Hey! Again, great work!
I was wondering why you subtract the bias here before adding it again?
https://github.com/NVIDIA/partialconv/blob/5b8f0a67d9baa8abdf2540904f2012a631f659a6/models/partialconv2d.py#L76

**Comment by liuguilin1225** [comment]
Because this line: https://github.com/NVIDIA/partialconv/blob/5b8f0a67d9baa8abdf2540904f2012a631f659a6/models/partialconv2d.py#L72 already includes the bias term. We don't want to do re-weighting on bias term.
