### ISSUE TITLE
papaer arch partial conv num question 

### ISSUE THREAD

**Issue by oneTaken** [NVIDIA/partialconv#26]
Hi, 
I have a question about arch design, I find in the paper in Section 3.2 which is:
> replacing all convolutional layers with partial convolutional layers and using nearest neighbor up-sampling in the decoding stage

The input have inpainting mask, so the partial conv is necessary.  
But on the middle feature maps, do it be ordinary conv is also okay?

**Comment by liuguilin1225** [comment]
Yes. That is what we did. All the masks are with values either 0 or 1.
