### ISSUE TITLE
How to test the image inpainting?

### ISSUE THREAD

**Issue by taasoo** [NVIDIA/partialconv#8]
The "main.py" is only training a model. How can I write a test.py to test the image inpainting? Input args?

**Comment by liuguilin1225** [comment]
@taasoo This repo doesn't contain the whole system for the inpainting. Instead, it contains the training and testing code for running partial conv based padding for classification. The partial conv layer in this repo is used in the inpainting. If you want to test an image, you can check the online demo: www.nvidia.com/research/inpainting (temporary down for some development; will be back). You can also send me your images if you want to run more examples. You can also check the third-party implementations on the github. (Some differences are discussed here: http://masc.cs.gmu.edu/wiki/partialconv )

**Comment by taasoo** [comment]
Thanks a lot!
